---
- name: Prepare Kubespray environment
  hosts: localhost
  gather_facts: no

  vars:
    kubespray_path: "{{ playbook_dir }}/kubespray"

  tasks:
    - name: Create Python virtual environment and install requirements
      shell: |
        python3 -m venv {{ kubespray_path }}/venv
        {{ kubespray_path }}/venv/bin/pip install --upgrade pip
        {{ kubespray_path }}/venv/bin/pip install -r {{ kubespray_path }}/requirements.txt
      args:
        creates: "{{ kubespray_path }}/venv/bin/ansible-playbook"

- name: Install Kubernetes
  ansible.builtin.import_playbook: kubespray/cluster.yml

